### ISSUE TITLE
YouTube embed not working?

### ISSUE THREAD

**Issue by alesrebec** [jcisio/MediaWrapper#5]
Did YouTube changed their API lately?

I get this for all YT embedded videos using MediaWrapper library and latest Drupal Internet Sources field formatter 7.x-1.x-dev module.

![screenshot from 2015-11-23 13 02 41](https://cloud.githubusercontent.com/assets/426177/11336123/f1030bd6-91e2-11e5-958d-26c7d9fcdb1b.png)

**Comment by jcisio** [comment]
Do you have the urls of the videos (is it really all videos)? Also the output markup (it should be an iframe). I don't have any problem at all.

**Comment by jcisio** [comment]
I've just found the problem. I think you upgraded the Link module. Please see https://www.drupal.org/project/isfield/issues/3110738
